# StyLua Configuration
# Syntax specification for Lua version (All, Lua51, Lua52, Lua53, Lua54, LuaJIT, Luau, CfxLua)
syntax = "All"

# Formatting constraints
column_width = 80
line_endings = "Unix"
indent_type = "Spaces"
indent_width = 4

# String formatting preferences
quote_style = "AutoPreferSingle"

# Function call formatting
call_parentheses = "Always"
space_after_function_names = "Never"

# Code structure
collapse_simple_statement = "Never"

# Module organization
[sort_requires]
enabled = true

